# protect-generated-files receives Claude Code's PreToolUse input of an Edit or a Write, and decides on the path alone.

setup() {
    # shellcheck source=helper.bash
    source "$BATS_TEST_DIRNAME/helper.bash"
    sandbox
    HOOK=$HOOKS/claude/protect-generated-files
    repo=$work/repo
    git init -q "$repo"
    mkdir -p "$repo/drinkit/drinkit-infra/src/generated/jooq/kotlin/tables" "$repo/deployment/local"
}

# Claude Code is about to write <file> with <tool>, Edit by default.
writes() {
    local tool=${2:-Edit}
    run_hook_on "pre-tool-use-$(echo "$tool" | tr '[:upper:]' '[:lower:]')" '.tool_input.file_path = $file' --arg file "$1"
    assert_success
}

refused() {
    writes "$@"
    assert_equal "$(jq -r .hookSpecificOutput.permissionDecision <<<"$output")" deny
}

allowed() {
    writes "$@"
    refute_output
}

@test "a jOOQ class is refused" {
    refused "$repo/drinkit/drinkit-infra/src/generated/jooq/kotlin/tables/Cellar.kt"
    assert_equal "$(jq -r .hookSpecificOutput.permissionDecisionReason <<<"$output")" \
        "protect-generated-files: this file is generated by jOOQ from the schema. Change the changelog, apply it, then run ./gradlew jooqCodegen, as the database-change skill says"
}
@test "a jOOQ class written whole is refused" { refused "$repo/drinkit/drinkit-infra/src/generated/jooq/kotlin/tables/Cellar.kt" Write; }
@test "a jOOQ class in a package not generated yet is refused" { refused "$repo/drinkit/drinkit-infra/src/generated/jooq/kotlin/bottles/Bottle.kt" Write; }
@test "the generated API client, never generated in this clone, is refused" { refused "$repo/drinkit/drinkit-frontend/src/openapi/apis/CellarsApi.ts" Write; }
@test "a Gradle lock file is refused" { refused "$repo/drinkit/drinkit-backend/gradle.lockfile"; }
@test "an npm lock file is refused" { refused "$repo/drinkit/drinkit-frontend/package-lock.json"; }
@test "an npm lock file at the root is refused" { refused "$repo/package-lock.json"; }
@test "a generated documentation page is refused" { refused "$repo/docs/src/engineering/resources/domains/cellar.md"; }
@test "a .env file is refused" { refused "$repo/deployment/local/.env"; }
@test "a .env file in a new folder is refused" { refused "$repo/deployment/staging/.env" Write; }
@test "a .env variant is refused" { refused "$repo/deployment/local/.env.local"; }
@test "a relative path is refused" { refused "drinkit/drinkit-infra/src/generated/jooq/kotlin/tables/Cellar.kt"; }
@test "a relative .env at the root is refused" { refused ".env"; }
@test "a path with spaces is refused" { refused "$work/my clone/drinkit/drinkit-infra/src/generated/jooq/kotlin/tables/Cellar.kt"; }
@test "a .env outside any repository is refused" { refused "$work/outside/.env"; }

@test "a Kotlin source is allowed" { allowed "$repo/drinkit/drinkit-infra/src/main/kotlin/JooqCellars.kt"; }
@test "a Vue page is allowed" { allowed "$repo/drinkit/drinkit-frontend/src/pages/index.vue"; }
@test "package.json is allowed" { allowed "$repo/drinkit/drinkit-frontend/package.json"; }
@test "a version catalog is allowed" { allowed "$repo/gradle/libs.versions.toml"; }
@test "the verification metadata is allowed" { allowed "$repo/gradle/verification-metadata.xml"; }
@test "a hand-written documentation page is allowed" { allowed "$repo/docs/src/engineering/harness.md"; }
@test "a .env template is allowed" { allowed "$repo/deployment/local/.env.example" Write; }
@test "a .env sample is allowed" { allowed "$repo/deployment/local/.env.sample"; }
@test "a file outside any repository is allowed" { allowed "$work/outside/notes.md" Write; }
@test "a source path with spaces is allowed" { allowed "$work/my clone/drinkit/drinkit-infra/src/main/kotlin/Cellar.kt"; }
