spring.docker.compose:
  life-cycle-management: start-only
  file: ${ROOT_FOLDER:}deployment/local/compose.yml
  skip.in-tests: true
  enabled: true

email.sender.enabled: false

springdoc:
  api-docs.enabled: true
  swagger-ui.enabled: true

meilisearch:
  url: http://localhost:7700
  apiKey: masterKey

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/drinkit
    username: drinkit
    password: admin

logging.level:
    org.springframework.security: DEBUG