volumes:
  postgresql-data:
  meilisearch-data:
  flipt-data:

services:
  postgresql:
    image: postgres:18.6@sha256:5a5a84b19854a9ffaa54082c166ff4ec27473a361e496e5ea167f298f2da9722
    ports:
      - "5432:5432"
    volumes:
      - postgresql-data:/var/lib/postgresql
    environment:
      POSTGRES_DB: drinkit
      POSTGRES_USER: drinkit
      POSTGRES_PASSWORD: admin

  meilisearch:
    image: getmeili/meilisearch:v1.54.1@sha256:6f6c72d43008f227a7329422aa723ab5b4929e1fad8e68743062b050c36fb7ad
    ports:
      - "7700:7700"
    volumes:
      - meilisearch-data:/meili_data
    environment:
      MEILI_MASTER_KEY: masterKey
      MEILI_NO_ANALYTICS: true
      MEILI_UPGRADE_DB: true

  flipt:
    image: flipt/flipt:v2.13.1@sha256:3118adad2f21d2d4793765265e9eb1c99b547019f062ce438430089ba7cea89b
    ports:
      - "8082:8080"
    volumes:
      - flipt-data:/var/opt/flipt # TODO change to real path