volumes:
  postgresql-data:
  meilisearch-data:

services:
  postgresql:
    image: postgres:17.4
    ports:
      - "5432:5432"
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: drinkit
      POSTGRES_USER: drinkit
      POSTGRES_PASSWORD: admin

  meilisearch:
    image: getmeili/meilisearch:v1.13.2
    ports:
      - "7700:7700"
    volumes:
      - meilisearch-data:/meili_data
    environment:
      MEILI_MASTER_KEY: masterKey
      MEILI_NO_ANALYTICS: true