spring:
  session:
    jdbc:
      initialize-schema: never
      table-name: drinkit_session.spring_session # Schema can't be easily provide by another property, so we hack the table name here

server:
  servlet:
    session:
      cookie:
        http-only: true
        secure: true
        name: SESSIONID
        same-site: none
        path: /
      tracking-modes: cookie
      timeout: 15m
  forward-headers-strategy: framework