name: Execute code analysis

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: read
  security-events: write  # for github/codeql-action/upload-sarif to upload SARIF results

jobs:
  code-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-home-cache-cleanup: true

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Run Detekt
        run: ./gradlew detekt detektReportMergeSarif --continue

      - name: Upload SARIF file to GitHub
        uses: github/codeql-action/upload-sarif@v3
        if: success() || failure()
        with:
          sarif_file: build/reports/detekt/detekt-all-projects.sarif
          category: detekt-code-analysis