name: Execute code analysis

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: read
  actions: read
  security-events: write

jobs:
  detekt-static-code-analysis:
    name: Detekt - Static Code Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-home-cache-cleanup: true

      - name: Make gradlew executable
        run: chmod +x ./gradlew

#      - name: Run Detekt
#        run: ./gradlew detekt detektReportMergeSarif --continue

#      - name: Upload SARIF file to GitHub
#        uses: github/codeql-action/upload-sarif@v3
#        if: success() || failure()
#        with:
#          sarif_file: build/reports/detekt/detekt-all-projects.sarif
#          category: detekt-code-analysis

#  codeql-static-code-analysis:
#    name: CodeQL - Static Code Analysis
#    runs-on: 'ubuntu-latest'
#    timeout-minutes: 360

#    steps:
#      - name: Checkout
#        uses: actions/checkout@v4

#      - name: Setup JDK 21
#        uses: actions/setup-java@v4
#        with:
#          distribution: temurin
#          java-version: 21

#      - name: Setup Gradle
#        uses: gradle/actions/setup-gradle@v3
#        with:
#          gradle-home-cache-cleanup: true

#      - name: Make gradlew executable
#        run: chmod +x ./gradlew

#      - name: Initialize CodeQL
#        uses: github/codeql-action/init@v3
#        with:
#          languages: 'java-kotlin'
#          queries: security-and-quality # https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning#using-queries-in-ql-packs

#      - name: Build Application
#        run: ./gradlew build -x test -x detekt

#      - name: Perform CodeQL Analysis
#        uses: github/codeql-action/analyze@v3
#        with:
#          category: codeql-kotlin-analysis
