name: Dependency Submission

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  dependency-submission:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup JDK 24
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 24

      - name: Setup Gradle to generate and submit dependency graphs
        uses: gradle/actions/setup-gradle@v4

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Execute Gradle build
        run: ./gradlew classes